version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  upload-files-service:
    build: .
    ports:
      - 3030:3030
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - SWAGGER_URL=${SWAGGER_URL}
    depends_on:
      - mongodb
